### ISSUE TITLE
Tree Feature Config Crash

### ISSUE THREAD

**Issue by WenXin20** [rehwinkel/treemendous#2]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Treemendous v0.4.1`

While exploring the world, I suddenly crashed. There may have been a Juniper Forest Hills nearby according to the crash log.
[Crash Report](https://gist.github.com/WenXin20/de5e1f08fd676b2c298011aac8ad840a)

**Comment by rehwinkel** [comment]
Fixed this bug in the most recent commit.

**Comment by WenXin20** [comment]
Thanks!
